name = "chomp-urls"
main = "src/index.js"
compatibility_date = "2024-01-20"

# KV namespace for storing short URLs
[[kv_namespaces]]
binding = "URLS"
id = "template_worker_views"

# Environment variables
[vars]
ADMIN_PASSWORD = "changeme"
